spring:
    datasource:
        username: ${POSTGRESQL_ADDON_USER}
        password: ${POSTGRESQL_ADDON_PASSWORD}
        url: jdbc:postgresql://${POSTGRESQL_ADDON_HOST}:${POSTGRESQL_ADDON_PORT}/${POSTGRESQL_ADDON_DB}
        driver-class-name: org.postgresql.Driver

    jpa:
        properties:
            hibernate:
                ddl-auto: create
                dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true


