com:
    auth:
        token: AUTHTOKEN
        expired: 30000
    csrf:
        token: XSRF-TOKEN
        header:
            token: X-XSRF-TOKEN

spring:
#    jpa:
#        properties:
#            hibernate:
#                dialect: org.hibernate.dialect.PostgreSQLDialect
    profiles:
        active: clever