com:
    auth:
        token: AUTHTOKEN
        expired: 30000
    csrf:
        token: XSRF-TOKEN
        header:
            token: X-XSRF-TOKEN

spring:
    h2:
        console:
            #http://localhost/h2-console
            enabled: true
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: root
        password: root

    jpa:
        show-sql: true
        properties:
            hibernate:
                ddl-auto: update
            format_sql: true
        generate-ddl: false
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update