spring:
    datasource:
        username: ${POSTGRESQL_ADDON_USER}
        password: ${POSTGRESQL_ADDON_PASSWORD}
        url: jdbc:postgresql://${POSTGRESQL_ADDON_HOST}:${POSTGRESQL_ADDON_PORT}/${POSTGRESQL_ADDON_DB}
        driver-class-name: org.postgresql.Driver

    h2:
        console:
            #http://localhost/h2-console
            enabled: true

    jpa:
        show-sql: true
        properties:
            format_sql: true
        generate-ddl: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create

